version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    open-pull-requests-limit: 10

    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "dev"
    # Labels on pull requests for version updates only
#     labels:
#       - "dependabot"
